
export const teamColors = [
  {
    "ATL": '#D70040',
    "BOS": "green",
    "BKN": "grey",
    "CHA": "teal",
    "CHI": "#D70040",
    "CLE": "#7B3F00",
    "DAL": "#0F52BA",
    "DEN": "lightblue",
    "DET": "#D70040",
    "GSW": "yellow",
    "HOU": "#D70040",
    "IND": "yellow",
    "LAC": "#0F52BA",
    "LAL": "purple",
    "MEM": "cornflowerblue",
    "MIA": "#D70040",
    "MIL": "green",
    "MIN": "green",
    "NOP": "#1434A4",
    "NYK": "orange",
    "OKC": "#0F52BA",
    "ORL": "lightblue",
    "PHI": "#D70040",
    "PHX": "purple",
    "POR": "#D70040",
    "SAC": "purple",
    "SAS": "grey",
    "TOR": "#D70040",
    "UTA": "#FFBF00",
    "WAS": "#0F52BA",
  }
]